/************************************************************************************************************************
Autor: OFVE,MSNTG,CJV, LAHP
Version : 1.2
Descripción : Query que obtiene los datos de crédito de ahorro (37/64) para el modelo de CHURN entrenamiento
Fuente: HANA
Notas : 
 1)modificar variables FECHA a la fecha de inicio de mes (AAAA-MM-01) *siempre a inicio de mes
Observaciones:
 - Se agrega el nivel de riesgo
 - Se modifica el CC para que sea a nivel producto de ahorro
 - Se agrega el desembolso en TDD (dispersión)
 - Se agrega el desembolso para ahorro e inversión al corte de mes (1M-8M)
 - Se realiza el cruce correcto a nivel crédito para los desembolsos y la dispersión, así como los productos padres las 
   inversiones para que el dato sea cruzado correcto con su cuenta de ahorro
 - Se agregan los tipos de txn crédito/desembolso (in) y compras (out)
 - Se agregan los meses de predicción M_1 y M_2 para las variables atemporales
 16/10/23 Se modifica la parte de transacciones de acuerdo a la revision del catálogo de transacciones realizada el 13 y 16 de octubre
		  Se eliminan las tablas temporales TX_IN_2m,SPEI_IN_2m,DEVOLUCIONES_IN_2m,DESEM_CRED_IN_2m,TX_OUT_2m,SPEI_OUT_2m,COMPRAS_OUT_2m
		  SALDOS_AH_2m,SALDOS_AH_CORTE_2m,SALDOS_INVER_2m,SALDOS_INVER_CORTE_2m
		  Se modifica el periodo a consultar transacciones de -8 a 2 meses despues de la fecha de inicio
		  Se coloca valor a igualdad cuando la comparación es de un solo valor.
 20/12/23 Se agrega transacciones no financieras y 4 códigos para transacciones cash in
 08/04/24 Se genera un nuevo flag de credito donde 1= crédito actual , 0 tuvo crédito en algún momento, -1 nunca ha tenido crédito 
 07/05/24 Se limitan categorias para la variable TRANSACTION_TYPE_CD  para concidedarar solamente financiera en cash_in y Cash_out
 07/06/24 Se limitan categorias para la variable TRANSACTION_TYPE_CD  para concidedarar no financieras y eliminan tablas devoluciones
 08/08/24 Se eliminan variables nivel de riesgo y tablas relacionadas, Se elimina variable de Dispersion creada como concatenacion de metodo y canal.
			Se cambian a variables ID el producto de credito y estatus de plastico
03/09/24 Se filtra a considerar cuentas que tengan mas de de una transaccion financiera.
15/10/24 Se elimina filtro donde se  consideraran cuentas que tengan mas de de una transaccion financiera.
15/10/24 Se alinean transacciones a aquellas que sean detonadas por el cliente.
15/10/24 Se cambian transacciones no financieras por transacciones no uso
17/10/24 Se Actualiza tabla base por FACT_ANALYTIC_AGREEMENT_DET_HIST para cuadrar informacion con microstrategy
18/10/24 Se agregan 7 dias para la fecha de credito en busqueda en DIM_CONTRACT_DISBURSEMENT_HIST
21/10/24 Se omite la variable DIM_ACCOUNT_START_DT para el calculo de la vigencia del plastico
23/10/24 Se anexa Centro de Costos
01/11/24 se modifica tabla para extraer BRANCH_OFFICE_ID
18/06/24 Limpieza de query y modificacion de estructura
21/07/26 Se comienza con el proceso de limpieza de la query para su optimizacion hacia Propension de compras
            inclusion de CTE, eliminacion de tablas innecesarias, eliminacion de las tablas locales, eliminacion de columnas no necesarias
*************************************************************************************************************************/

SET 'FECHA' = '2026-06-01';

    WITH
    -- Universo 37 y 64
    UNIVERSO_INVER37_64 AS (
        SELECT
        AC.CUSTOMER_ID AS NUM_CLIENTE,
        AC.ACCOUNT_ID AS NUM_CUENTA_AHORRO,
        AC.ACCOUNT_NUM AS CUENTA_AHORRO,
        AB.BALANCE_AMT AS SALDO_CORTE,
        EV.BENEFITS_CENTER_ORIG_CD as OFICINA_SERVICIO,
        MONTHS_BETWEEN(AH.ACCOUNT_OPENING_DT,LAST_DAY(CAST(SESSION_CONTEXT('FECHA') AS DATE))) AS ANTIGUEDAD_AHORRO,
        --ROW_NUMBER() OVER (PARTITION BY AC.CUSTOMER_ID,AC.ACCOUNT_ID ORDER BY VLDC.CARD_EXPIRATION_DT desc) AS REG
            FROM DP_SEM_EXP.FACT_ANALYTIC_AGREEMENT_DET_HIST AS AC
            LEFT JOIN DP_SEM_EXP.DIM_AGREEMENT_BALANCE_HIST AS AB ON (AB.ACCOUNT_ID=AC.ACCOUNT_ID AND AGREEMENT_BALANCE_START_DT = LAST_DAY(CAST(SESSION_CONTEXT('FECHA') AS DATE)))
            --LEFT JOIN DP_SEM_EXP.DIM_PRODUCT AS PR ON (PR.PRODUCT_ID=AC.PRODUCT_ID)
            --LEFT JOIN dp_sem_exp.DIM_AGREEMENT_STATUS_TYPE AS DAST ON (DAST.AGREEMENT_STATUS_CD = AC.ACCOUNT_STATUS_CD)
            --LEFT JOIN dp_bi_deposit.DIM_ACCOUNTS AS DA ON (DA.ACCOUNT_ID = AC.ACCOUNT_ID AND
              --  LAST_DAY(CAST(SESSION_CONTEXT('FECHA') AS DATE)) BETWEEN DA.DIM_ACCOUNT_START_DT AND coalesce(DA.DIM_ACCOUNT_END_DT,cast('9999-01-01' AS date)))
            LEFT JOIN DP_SEM_EXP.DIM_BRANCH_OFFICE_HIST AS EV ON (EV.BRANCH_OFFICE_ID=AC.BRANCH_OFFICE_ID)
                AND ADD_DAYS(LAST_DAY(CAST(SESSION_CONTEXT('FECHA') AS DATE)),7) BETWEEN EV.BRANCH_OFFICE_START_DT AND coalesce(EV.BRANCH_OFFICE_END_DT,cast('9999-01-01' AS date))
            --LEFT JOIN DP_SEM_EXP.VLD_CARD AS VLDC ON (AC.ACCOUNT_ID = VLDC.ACCOUNT_ID AND
              --  LAST_DAY(CAST(SESSION_CONTEXT('FECHA') AS DATE)) BETWEEN CARD_CONTRACT_START_DT AND coalesce(CARD_CONTRACT_END_DT,cast('9999-01-01' AS date)))
            LEFT JOIN dp_sem_exp.DIM_AGREEMENT_ACCOUNT_HIST AS AH ON (AC.ACCOUNT_ID=AH.ACCOUNT_ID)
                AND LAST_DAY(CAST(SESSION_CONTEXT('FECHA') AS DATE)) BETWEEN AH.AGREEMENT_ACCOUNT_START_DT and coalesce(AH.AGREEMENT_ACCOUNT_END_DT,cast('9999-01-01' AS date))
            WHERE period_dt = LAST_DAY(CAST(SESSION_CONTEXT('FECHA') AS DATE))
            AND AC.ACCOUNT_STATUS_CD IN (2,3)
            AND (AC.FLG_ACTIVE_AGREEMENT_ACCOUNT_CRED=1 OR AC.FLG_ACTIVE_AGREEMENT_ACCOUNT_Ma=1)
            AND AC.PRODUCT_ID IN (37,64) 
    ),
    -- Universo 70
    UNIVERSO_INVER70 AS (
        SELECT
        AC.CUSTOMER_ID as NUM_CLIENTE,
        DAFT.PIVOT_ACCOUNT_ID
            FROM DP_SEM_EXP.FACT_ANALYTIC_AGREEMENT_DET_HIST AS AC
                --LEFT JOIN DP_SEM_EXP.DIM_AGREEMENT_BALANCE_HIST AS AB ON (AB.ACCOUNT_ID=AC.ACCOUNT_ID AND AB.AGREEMENT_BALANCE_START_DT = LAST_DAY(CAST(SESSION_CONTEXT('FECHA') AS DATE)))
                LEFT JOIN DP_SEM_EXP.VLD_DEPOSIT_AGREEMENT_FIXED_TERM AS DAFT ON (AC.ACCOUNT_ID=DAFT.ACCOUNT_ID AND LAST_DAY(CAST(SESSION_CONTEXT('FECHA') AS DATE)) BETWEEN AGREEMENT_START_DT AND coalesce(AGREEMENT_END_DT,cast('9999-01-01' AS date)))
            WHERE period_dt = LAST_DAY(CAST(SESSION_CONTEXT('FECHA') AS DATE))
                AND (AC.FLG_ACTIVE_AGREEMENT_ACCOUNT_CRED=1 or AC.FLG_ACTIVE_AGREEMENT_ACCOUNT_Ma=1)
                AND AC.ACCOUNT_STATUS_CD IN (2,3)
                AND AC.PRODUCT_ID=70
                AND AC.customer_id in (SELECT NUM_CLIENTE FROM UNIVERSO_INVER37_64)
            GROUP BY AC.CUSTOMER_ID,DAFT.PIVOT_ACCOUNT_ID
    ),

    -- Parametros para fechas
    Parametros AS (
        SELECT 
            CAST(SESSION_CONTEXT('FECHA') AS DATE) AS FECHA_REF,
            ADD_MONTHS(CAST(SESSION_CONTEXT('FECHA') AS DATE), -8) AS FECHA_INI,
            LAST_DAY(CAST(SESSION_CONTEXT('FECHA') AS DATE)) AS FECHA_FIN
        FROM DUMMY
    ),
    -- Formato de meses (YYYYMM)
    MESES AS (
       SELECT 
            (YEAR(ADD_MONTHS(FECHA_REF, 0)) * 100 + MONTH(ADD_MONTHS(FECHA_REF, 0))) AS K0,
            (YEAR(ADD_MONTHS(FECHA_REF, -1)) * 100 + MONTH(ADD_MONTHS(FECHA_REF, -1))) AS K1,
            (YEAR(ADD_MONTHS(FECHA_REF, -2)) * 100 + MONTH(ADD_MONTHS(FECHA_REF, -2))) AS K2,
            (YEAR(ADD_MONTHS(FECHA_REF, -3)) * 100 + MONTH(ADD_MONTHS(FECHA_REF, -3))) AS K3,
            (YEAR(ADD_MONTHS(FECHA_REF, -4)) * 100 + MONTH(ADD_MONTHS(FECHA_REF, -4))) AS K4,
            (YEAR(ADD_MONTHS(FECHA_REF, -5)) * 100 + MONTH(ADD_MONTHS(FECHA_REF, -5))) AS K5,
            (YEAR(ADD_MONTHS(FECHA_REF, -6)) * 100 + MONTH(ADD_MONTHS(FECHA_REF, -6))) AS K6,
            (YEAR(ADD_MONTHS(FECHA_REF, -7)) * 100 + MONTH(ADD_MONTHS(FECHA_REF, -7))) AS K7,
            (YEAR(ADD_MONTHS(FECHA_REF, -8)) * 100 + MONTH(ADD_MONTHS(FECHA_REF, -8))) AS K8
        FROM Parametros
    ),

    -- Tabla TX_IN
    Datos_TX_IN AS (
       SELECT 
            E.CONTRACT_AGREEMENT_ID AS NUM_CUENTA_AHORRO,
            E.EVENT_AMNT AS MONTO_TRANSAC,
            (YEAR(E.EVENT_EFF_DT) * 100 + MONTH(E.EVENT_EFF_DT)) AS EVENT_KEY
        FROM DP_DWV.DEPOSIT_AGREEMENT_EVENT AS E
        CROSS JOIN Parametros AS P
        WHERE E.TRANSACTION_TYPE_CD IN (3136, 3107, 3108, 3436, 3132, 3131, 3442, 1049, 1050)
          AND E.EVENT_EFF_DT BETWEEN P.FECHA_INI AND P.FECHA_FIN
          AND E.CONTRACT_AGREEMENT_ID IN (SELECT NUM_CUENTA_AHORRO FROM UNIVERSO_INVER37_64)
    ),
    TX_IN AS (
       SELECT 
        D.NUM_CUENTA_AHORRO,
        SUM(CASE WHEN D.EVENT_KEY = M.K8 THEN D.MONTO_TRANSAC END) AS MONTO_TRANSAC_IN_M8,
        COUNT(CASE WHEN D.EVENT_KEY = M.K8 THEN D.NUM_CUENTA_AHORRO END) AS TOT_MONTO_TX_IN_M8,
        SUM(CASE WHEN D.EVENT_KEY = M.K7 THEN D.MONTO_TRANSAC END) AS MONTO_TRANSAC_IN_M7,
        COUNT(CASE WHEN D.EVENT_KEY = M.K7 THEN D.NUM_CUENTA_AHORRO END) AS TOT_MONTO_TX_IN_M7,
        SUM(CASE WHEN D.EVENT_KEY = M.K6 THEN D.MONTO_TRANSAC END) AS MONTO_TRANSAC_IN_M6,
        COUNT(CASE WHEN D.EVENT_KEY = M.K6 THEN D.NUM_CUENTA_AHORRO END) AS TOT_MONTO_TX_IN_M6,
        SUM(CASE WHEN D.EVENT_KEY = M.K5 THEN D.MONTO_TRANSAC END) AS MONTO_TRANSAC_IN_M5,
        COUNT(CASE WHEN D.EVENT_KEY = M.K5 THEN D.NUM_CUENTA_AHORRO END) AS TOT_MONTO_TX_IN_M5,
        SUM(CASE WHEN D.EVENT_KEY = M.K4 THEN D.MONTO_TRANSAC END) AS MONTO_TRANSAC_IN_M4,
        COUNT(CASE WHEN D.EVENT_KEY = M.K4 THEN D.NUM_CUENTA_AHORRO END) AS TOT_MONTO_TX_IN_M4,
        SUM(CASE WHEN D.EVENT_KEY = M.K3 THEN D.MONTO_TRANSAC END) AS MONTO_TRANSAC_IN_M3,
        COUNT(CASE WHEN D.EVENT_KEY = M.K3 THEN D.NUM_CUENTA_AHORRO END) AS TOT_MONTO_TX_IN_M3,
        SUM(CASE WHEN D.EVENT_KEY = M.K2 THEN D.MONTO_TRANSAC END) AS MONTO_TRANSAC_IN_M2,
        COUNT(CASE WHEN D.EVENT_KEY = M.K2 THEN D.NUM_CUENTA_AHORRO END) AS TOT_MONTO_TX_IN_M2,
        SUM(CASE WHEN D.EVENT_KEY = M.K1 THEN D.MONTO_TRANSAC END) AS MONTO_TRANSAC_IN_M1,
        COUNT(CASE WHEN D.EVENT_KEY = M.K1 THEN D.NUM_CUENTA_AHORRO END) AS TOT_MONTO_TX_IN_M1,
        SUM(CASE WHEN D.EVENT_KEY = M.K0 THEN D.MONTO_TRANSAC END) AS MONTO_TRANSAC_IN_M0,
        COUNT(CASE WHEN D.EVENT_KEY = M.K0 THEN D.NUM_CUENTA_AHORRO END) AS TOT_MONTO_TX_IN_M0
    FROM Datos_TX_IN AS D
    CROSS JOIN MESES AS M
    GROUP BY D.NUM_CUENTA_AHORRO
    ),

    --Tabla TX_OUT
    Datos_TX_OUT AS (
        SELECT 
            E.CONTRACT_AGREEMENT_ID AS NUM_CUENTA_AHORRO,
            E.EVENT_AMNT AS MONTO_TRANSAC,
            (YEAR(E.EVENT_EFF_DT) * 100 + MONTH(E.EVENT_EFF_DT)) AS EVENT_KEY
        FROM DP_DWV.DEPOSIT_AGREEMENT_EVENT AS E
        CROSS JOIN Parametros AS P
        WHERE E.TRANSACTION_TYPE_CD IN (1018,3591,3047,3048,3416,3315,3410,3461,1013,3317,3460,3420,3421,3046,3416,1005,1000,3728,3190,999)
          AND E.EVENT_EFF_DT BETWEEN P.FECHA_INI AND P.FECHA_FIN
          AND E.CONTRACT_AGREEMENT_ID IN (SELECT NUM_CUENTA_AHORRO FROM UNIVERSO_INVER37_64)
    ),
    TX_OUT AS (
    SELECT 
        D.NUM_CUENTA_AHORRO,
        COUNT(CASE WHEN D.EVENT_KEY = M.K8 THEN D.NUM_CUENTA_AHORRO END) AS TOT_MONTO_TX_OUT_M8,
        COUNT(CASE WHEN D.EVENT_KEY = M.K7 THEN D.NUM_CUENTA_AHORRO END) AS TOT_MONTO_TX_OUT_M7,
        COUNT(CASE WHEN D.EVENT_KEY = M.K6 THEN D.NUM_CUENTA_AHORRO END) AS TOT_MONTO_TX_OUT_M6,
        COUNT(CASE WHEN D.EVENT_KEY = M.K5 THEN D.NUM_CUENTA_AHORRO END) AS TOT_MONTO_TX_OUT_M5,
        COUNT(CASE WHEN D.EVENT_KEY = M.K4 THEN D.NUM_CUENTA_AHORRO END) AS TOT_MONTO_TX_OUT_m4,
        COUNT(CASE WHEN D.EVENT_KEY = M.K3 THEN D.NUM_CUENTA_AHORRO END) AS TOT_MONTO_TX_OUT_M3,
        COUNT(CASE WHEN D.EVENT_KEY = M.K2 THEN D.NUM_CUENTA_AHORRO END) AS TOT_MONTO_TX_OUT_M2,
        COUNT(CASE WHEN D.EVENT_KEY = M.K1 THEN D.NUM_CUENTA_AHORRO END) AS TOT_MONTO_TX_OUT_M1,
        COUNT(CASE WHEN D.EVENT_KEY = M.K0 THEN D.NUM_CUENTA_AHORRO END) AS TOT_MONTO_TX_OUT_M0
    FROM Datos_TX_OUT AS D
    CROSS JOIN MESES AS M
    GROUP BY D.NUM_CUENTA_AHORRO
    ),

    -- Tabla SPEI_IN
    Datos_SPEI_IN AS (
        SELECT 
            E.CONTRACT_AGREEMENT_ID AS NUM_CUENTA_AHORRO,
            E.EVENT_AMNT AS MONTO_TRANSAC,
            (YEAR(E.EVENT_EFF_DT) * 100 + MONTH(E.EVENT_EFF_DT)) AS EVENT_KEY
        FROM DP_DWV.DEPOSIT_AGREEMENT_EVENT AS E
        CROSS JOIN Parametros AS P
        WHERE E.TRANSACTION_TYPE_CD =3136 --SPEI IN
          AND E.EVENT_EFF_DT BETWEEN P.FECHA_INI AND P.FECHA_FIN
          AND E.CONTRACT_AGREEMENT_ID IN (SELECT NUM_CUENTA_AHORRO FROM UNIVERSO_INVER37_64)
    ),
    SPEI_IN AS (
        SELECT 
        D.NUM_CUENTA_AHORRO,
        COUNT(CASE WHEN D.EVENT_KEY = M.K1 THEN D.NUM_CUENTA_AHORRO END) AS TOT_SPEI_TX_IN_M1,
        COUNT(CASE WHEN D.EVENT_KEY = M.K0 THEN D.NUM_CUENTA_AHORRO END) AS TOT_SPEI_TX_IN_M0,
        SUM(CASE WHEN D.EVENT_KEY = M.K8 THEN D.MONTO_TRANSAC END) AS MONTO_SPEI_IN_M8,
        SUM(CASE WHEN D.EVENT_KEY = M.K7 THEN D.MONTO_TRANSAC END) AS MONTO_SPEI_IN_M7,
        SUM(CASE WHEN D.EVENT_KEY = M.K6 THEN D.MONTO_TRANSAC END) AS MONTO_SPEI_IN_M6,
        SUM(CASE WHEN D.EVENT_KEY = M.K5 THEN D.MONTO_TRANSAC END) AS MONTO_SPEI_IN_M5,
        SUM(CASE WHEN D.EVENT_KEY = M.K4 THEN D.MONTO_TRANSAC END) AS MONTO_SPEI_IN_M4,
        SUM(CASE WHEN D.EVENT_KEY = M.K3 THEN D.MONTO_TRANSAC END) AS MONTO_SPEI_IN_M3,
        SUM(CASE WHEN D.EVENT_KEY = M.K2 THEN D.MONTO_TRANSAC END) AS MONTO_SPEI_IN_M2,
        SUM(CASE WHEN D.EVENT_KEY = M.K1 THEN D.MONTO_TRANSAC END) AS MONTO_SPEI_IN_M1,
        SUM(CASE WHEN D.EVENT_KEY = M.K0 THEN D.MONTO_TRANSAC END) AS MONTO_SPEI_IN_M0
    FROM Datos_SPEI_IN AS D
    CROSS JOIN MESES AS M
    GROUP BY D.NUM_CUENTA_AHORRO
    ),

    --Tabla SPEI_OUT
    Datos_SPEI_OUT AS (
        SELECT 
            E.CONTRACT_AGREEMENT_ID AS NUM_CUENTA_AHORRO,
            E.EVENT_AMNT AS MONTO_TRANSAC,
            (YEAR(E.EVENT_EFF_DT) * 100 + MONTH(E.EVENT_EFF_DT)) AS EVENT_KEY
        FROM DP_DWV.DEPOSIT_AGREEMENT_EVENT AS E
        CROSS JOIN Parametros AS P
        WHERE TRANSACTION_TYPE_CD IN (1018,3591) --SPEI OUT
          AND E.EVENT_EFF_DT BETWEEN P.FECHA_INI AND P.FECHA_FIN
          AND E.CONTRACT_AGREEMENT_ID IN (SELECT NUM_CUENTA_AHORRO FROM UNIVERSO_INVER37_64)
    ),
    SPEI_OUT AS (
    SELECT 
        D.NUM_CUENTA_AHORRO,
        SUM(CASE WHEN D.EVENT_KEY = M.K8 THEN D.MONTO_TRANSAC END) AS MONTO_SPEI_OUT_M8,
        SUM(CASE WHEN D.EVENT_KEY = M.K7 THEN D.MONTO_TRANSAC END) AS MONTO_SPEI_OUT_M7,
        SUM(CASE WHEN D.EVENT_KEY = M.K6 THEN D.MONTO_TRANSAC END) AS MONTO_SPEI_OUT_M6,
        SUM(CASE WHEN D.EVENT_KEY = M.K5 THEN D.MONTO_TRANSAC END) AS MONTO_SPEI_OUT_M5,
        SUM(CASE WHEN D.EVENT_KEY = M.K4 THEN D.MONTO_TRANSAC END) AS MONTO_SPEI_OUT_M4,
        SUM(CASE WHEN D.EVENT_KEY = M.K3 THEN D.MONTO_TRANSAC END) AS MONTO_SPEI_OUT_M3,
        SUM(CASE WHEN D.EVENT_KEY = M.K2 THEN D.MONTO_TRANSAC END) AS MONTO_SPEI_OUT_M2,
        SUM(CASE WHEN D.EVENT_KEY = M.K1 THEN D.MONTO_TRANSAC END) AS MONTO_SPEI_OUT_M1,
        SUM(CASE WHEN D.EVENT_KEY = M.K0 THEN D.MONTO_TRANSAC END) AS MONTO_SPEI_OUT_M0
    FROM Datos_SPEI_OUT AS D
    CROSS JOIN MESES AS M
    GROUP BY D.NUM_CUENTA_AHORRO
    ),

    -- Tabla COMPRAS_OUT
    Datos_COMPRAS_OUT AS (
        SELECT 
            E.CONTRACT_AGREEMENT_ID AS NUM_CUENTA_AHORRO,
            E.EVENT_AMNT AS MONTO_TRANSAC,
            (YEAR(E.EVENT_EFF_DT) * 100 + MONTH(E.EVENT_EFF_DT)) AS EVENT_KEY
        FROM DP_DWV.DEPOSIT_AGREEMENT_EVENT AS E
        CROSS JOIN Parametros AS P
        WHERE TRANSACTION_TYPE_CD IN (3048,3461,3460,3317) --COMPRAS
          AND E.EVENT_EFF_DT BETWEEN P.FECHA_INI AND P.FECHA_FIN
          AND E.CONTRACT_AGREEMENT_ID IN (SELECT NUM_CUENTA_AHORRO FROM UNIVERSO_INVER37_64)
    ),
    COMPRAS_OUT AS (
        SELECT 
        D.NUM_CUENTA_AHORRO,
        SUM(CASE WHEN D.EVENT_KEY = M.K8 THEN D.MONTO_TRANSAC END) AS MONTO_COMPRAS_OUT_M8,
        COUNT(CASE WHEN D.EVENT_KEY = M.K8 THEN D.NUM_CUENTA_AHORRO END) AS TOT_COMPRAS_TX_OUT_M8,
        SUM(CASE WHEN D.EVENT_KEY = M.K7 THEN D.MONTO_TRANSAC END) AS MONTO_COMPRAS_OUT_M7,
        COUNT(CASE WHEN D.EVENT_KEY = M.K7 THEN D.NUM_CUENTA_AHORRO END) AS TOT_COMPRAS_TX_OUT_M7,
        SUM(CASE WHEN D.EVENT_KEY = M.K6 THEN D.MONTO_TRANSAC END) AS MONTO_COMPRAS_OUT_M6,
        COUNT(CASE WHEN D.EVENT_KEY = M.K6 THEN D.NUM_CUENTA_AHORRO END) AS TOT_COMPRAS_TX_OUT_M6,
        SUM(CASE WHEN D.EVENT_KEY = M.K5 THEN D.MONTO_TRANSAC END) AS MONTO_COMPRAS_OUT_M5,
        COUNT(CASE WHEN D.EVENT_KEY = M.K5 THEN D.NUM_CUENTA_AHORRO END) AS TOT_COMPRAS_TX_OUT_M5,
        SUM(CASE WHEN D.EVENT_KEY = M.K4 THEN D.MONTO_TRANSAC END) AS MONTO_COMPRAS_OUT_M4,
        COUNT(CASE WHEN D.EVENT_KEY = M.K4 THEN D.NUM_CUENTA_AHORRO END) AS TOT_COMPRAS_TX_OUT_M4,
        SUM(CASE WHEN D.EVENT_KEY = M.K3 THEN D.MONTO_TRANSAC END) AS MONTO_COMPRAS_OUT_M3,
        COUNT(CASE WHEN D.EVENT_KEY = M.K3 THEN D.NUM_CUENTA_AHORRO END) AS TOT_COMPRAS_TX_OUT_M3,
        SUM(CASE WHEN D.EVENT_KEY = M.K2 THEN D.MONTO_TRANSAC END) AS MONTO_COMPRAS_OUT_M2,
        COUNT(CASE WHEN D.EVENT_KEY = M.K2 THEN D.NUM_CUENTA_AHORRO END) AS TOT_COMPRAS_TX_OUT_M2,
        SUM(CASE WHEN D.EVENT_KEY = M.K1 THEN D.MONTO_TRANSAC END) AS MONTO_COMPRAS_OUT_M1,
        COUNT(CASE WHEN D.EVENT_KEY = M.K1 THEN D.NUM_CUENTA_AHORRO END) AS TOT_COMPRAS_TX_OUT_M1,
        SUM(CASE WHEN D.EVENT_KEY = M.K0 THEN D.MONTO_TRANSAC END) AS MONTO_COMPRAS_OUT_M0,
        COUNT(CASE WHEN D.EVENT_KEY = M.K0 THEN D.NUM_CUENTA_AHORRO END) AS TOT_COMPRAS_TX_OUT_M0
    FROM Datos_COMPRAS_OUT AS D
    CROSS JOIN MESES AS M
    GROUP BY D.NUM_CUENTA_AHORRO
    ),

    --Tabla DESEM_CRED_IN
    Datos_DESEM_CRED_IN AS (
        SELECT 
            E.CONTRACT_AGREEMENT_ID AS NUM_CUENTA_AHORRO,
            E.EVENT_AMNT AS MONTO_TRANSAC,
            (YEAR(E.EVENT_EFF_DT) * 100 + MONTH(E.EVENT_EFF_DT)) AS EVENT_KEY
        FROM DP_DWV.DEPOSIT_AGREEMENT_EVENT AS E
        CROSS JOIN Parametros AS P
        WHERE E.TRANSACTION_TYPE_CD IN (3107) 
          AND E.EVENT_EFF_DT BETWEEN P.FECHA_INI AND P.FECHA_FIN
          AND E.CONTRACT_AGREEMENT_ID IN (SELECT NUM_CUENTA_AHORRO FROM UNIVERSO_INVER37_64)
    ),
    DESEM_CRED_IN AS (
    SELECT 
        D.NUM_CUENTA_AHORRO,
        SUM(CASE WHEN D.EVENT_KEY = M.K8 THEN D.MONTO_TRANSAC END) AS MONTO_DESEM_CRED_IN_M8,
        SUM(CASE WHEN D.EVENT_KEY = M.K7 THEN D.MONTO_TRANSAC END) AS MONTO_DESEM_CRED_IN_M7,
        SUM(CASE WHEN D.EVENT_KEY = M.K6 THEN D.MONTO_TRANSAC END) AS MONTO_DESEM_CRED_IN_M6,
        SUM(CASE WHEN D.EVENT_KEY = M.K5 THEN D.MONTO_TRANSAC END) AS MONTO_DESEM_CRED_IN_M5,
        SUM(CASE WHEN D.EVENT_KEY = M.K4 THEN D.MONTO_TRANSAC END) AS MONTO_DESEM_CRED_IN_M4,
        SUM(CASE WHEN D.EVENT_KEY = M.K3 THEN D.MONTO_TRANSAC END) AS MONTO_DESEM_CRED_IN_M3,
        SUM(CASE WHEN D.EVENT_KEY = M.K2 THEN D.MONTO_TRANSAC END) AS MONTO_DESEM_CRED_IN_M2,
        SUM(CASE WHEN D.EVENT_KEY = M.K1 THEN D.MONTO_TRANSAC END) AS MONTO_DESEM_CRED_IN_M1,
        SUM(CASE WHEN D.EVENT_KEY = M.K0 THEN D.MONTO_TRANSAC END) AS MONTO_DESEM_CRED_IN_M0
    FROM Datos_DESEM_CRED_IN AS D
    CROSS JOIN MESES AS M
    GROUP BY D.NUM_CUENTA_AHORRO
    ),

    --Tabla SALDOS_AH
    Datos_SALDOS_AH AS (
        SELECT
            F.CUSTOMER_ID,
            F.ACCOUNT_ID,
            F.DB_BALANCE_AVG_AMT,
            (YEAR(F.PROCESS_DT) * 100 + MONTH(F.PROCESS_DT)) AS PROCESS_KEY,
            ROW_NUMBER() OVER (
                PARTITION BY F.ACCOUNT_ID, YEAR(F.PROCESS_DT), MONTH(F.PROCESS_DT) 
                ORDER BY F.PROCESS_DT DESC
            ) AS REG
        FROM DP_BI_DEPOSIT.FACT_ACCOUNTS AS F
        CROSS JOIN Parametros AS P
        WHERE (F.CUSTOMER_ID, F.ACCOUNT_ID) IN (SELECT NUM_CLIENTE, NUM_CUENTA_AHORRO FROM UNIVERSO_INVER37_64)
          AND F.PROCESS_DT BETWEEN P.FECHA_INI AND P.FECHA_FIN
          AND F.DB_PRODUCT_ID IN (152, 153, 160)
    ),
    SALDOS_AH AS (
        SELECT
        D.CUSTOMER_ID,
        D.ACCOUNT_ID,
        SUM(CASE WHEN D.PROCESS_KEY = M.K8 THEN D.DB_BALANCE_AVG_AMT END) AS SALDO_AH_M8,
        SUM(CASE WHEN D.PROCESS_KEY = M.K7 THEN D.DB_BALANCE_AVG_AMT END) AS SALDO_AH_M7,
        SUM(CASE WHEN D.PROCESS_KEY = M.K6 THEN D.DB_BALANCE_AVG_AMT END) AS SALDO_AH_M6,
        SUM(CASE WHEN D.PROCESS_KEY = M.K5 THEN D.DB_BALANCE_AVG_AMT END) AS SALDO_AH_M5,
        SUM(CASE WHEN D.PROCESS_KEY = M.K4 THEN D.DB_BALANCE_AVG_AMT END) AS SALDO_AH_M4,
        SUM(CASE WHEN D.PROCESS_KEY = M.K3 THEN D.DB_BALANCE_AVG_AMT END) AS SALDO_AH_M3,
        SUM(CASE WHEN D.PROCESS_KEY = M.K2 THEN D.DB_BALANCE_AVG_AMT END) AS SALDO_AH_M2,
        SUM(CASE WHEN D.PROCESS_KEY = M.K1 THEN D.DB_BALANCE_AVG_AMT END) AS SALDO_AH_M1,
        SUM(CASE WHEN D.PROCESS_KEY = M.K0 THEN D.DB_BALANCE_AVG_AMT END) AS SALDO_AH_M0 
    FROM Datos_SALDOS_AH AS D
    CROSS JOIN MESES AS M
    WHERE D.REG = 1
    GROUP BY D.CUSTOMER_ID, D.ACCOUNT_ID
    ),

    --Tabla SALDOS_AH_CORTE
    Datos_SALDOS_AH_CORTE AS (
        SELECT
            F.CUSTOMER_ID,
            F.ACCOUNT_ID,
            F.DB_BALANCE_AMT,
            (YEAR(F.PROCESS_DT) * 100 + MONTH(F.PROCESS_DT)) AS PROCESS_KEY,
            ROW_NUMBER() OVER (
                PARTITION BY F.ACCOUNT_ID, YEAR(F.PROCESS_DT), MONTH(F.PROCESS_DT) 
                ORDER BY F.PROCESS_DT DESC
            ) AS REG
        FROM DP_BI_DEPOSIT.FACT_ACCOUNTS AS F
        CROSS JOIN Parametros AS P
        WHERE (F.CUSTOMER_ID, F.ACCOUNT_ID) IN (SELECT NUM_CLIENTE, NUM_CUENTA_AHORRO FROM UNIVERSO_INVER37_64)
          AND F.PROCESS_DT BETWEEN P.FECHA_INI AND P.FECHA_FIN
    ),
    SALDOS_AH_CORTE AS (
        SELECT
        D.CUSTOMER_ID,
        D.ACCOUNT_ID,
        SUM(CASE WHEN D.PROCESS_KEY = M.K8 THEN D.DB_BALANCE_AMT END) AS SALDO_CORTE_AH_M8,
        SUM(CASE WHEN D.PROCESS_KEY = M.K7 THEN D.DB_BALANCE_AMT END) AS SALDO_CORTE_AH_M7,
        SUM(CASE WHEN D.PROCESS_KEY = M.K6 THEN D.DB_BALANCE_AMT END) AS SALDO_CORTE_AH_M6,
        SUM(CASE WHEN D.PROCESS_KEY = M.K5 THEN D.DB_BALANCE_AMT END) AS SALDO_CORTE_AH_M5,
        SUM(CASE WHEN D.PROCESS_KEY = M.K4 THEN D.DB_BALANCE_AMT END) AS SALDO_CORTE_AH_M4,
        SUM(CASE WHEN D.PROCESS_KEY = M.K3 THEN D.DB_BALANCE_AMT END) AS SALDO_CORTE_AH_M3,
        SUM(CASE WHEN D.PROCESS_KEY = M.K2 THEN D.DB_BALANCE_AMT END) AS SALDO_CORTE_AH_M2,
        SUM(CASE WHEN D.PROCESS_KEY = M.K1 THEN D.DB_BALANCE_AMT END) AS SALDO_CORTE_AH_M1,
        SUM(CASE WHEN D.PROCESS_KEY = M.K0 THEN D.DB_BALANCE_AMT END) AS SALDO_CORTE_AH_M0
    FROM Datos_SALDOS_AH_CORTE AS D
    CROSS JOIN MESES AS M
    WHERE D.REG = 1
    GROUP BY D.CUSTOMER_ID, D.ACCOUNT_ID
    ),

    --Tabla SALDOS_INVER
    Datos_SALDOS_INVER AS (
        SELECT
            F.CUSTOMER_ID,
            DAFT.PIVOT_ACCOUNT_ID,
            F.DB_BALANCE_AVG_AMT,
            (YEAR(F.PROCESS_DT) * 100 + MONTH(F.PROCESS_DT)) AS PROCESS_KEY,
            ROW_NUMBER() OVER (
                PARTITION BY F.ACCOUNT_ID, YEAR(F.PROCESS_DT), MONTH(F.PROCESS_DT) 
                ORDER BY F.PROCESS_DT DESC
            ) AS REG
        FROM DP_BI_DEPOSIT.FACT_ACCOUNTS AS F
        CROSS JOIN Parametros AS P
        LEFT JOIN DP_SEM_EXP.VLD_DEPOSIT_AGREEMENT_FIXED_TERM AS DAFT 
            ON F.ACCOUNT_ID = DAFT.ACCOUNT_ID 
            AND P.FECHA_FIN BETWEEN DAFT.AGREEMENT_START_DT AND COALESCE(DAFT.AGREEMENT_END_DT, '9999-01-01')
        WHERE F.CUSTOMER_ID IN (SELECT NUM_CLIENTE FROM UNIVERSO_INVER70)
          AND F.PROCESS_DT BETWEEN P.FECHA_INI AND P.FECHA_FIN
          AND F.DB_PRODUCT_ID = 162
    ),
    SALDOS_INVER AS (
        SELECT
        D.CUSTOMER_ID,
        D.PIVOT_ACCOUNT_ID,
        SUM(CASE WHEN D.PROCESS_KEY = M.K8 THEN D.DB_BALANCE_AVG_AMT END) AS SALDO_INV_M8,
        SUM(CASE WHEN D.PROCESS_KEY = M.K7 THEN D.DB_BALANCE_AVG_AMT END) AS SALDO_INV_M7,
        SUM(CASE WHEN D.PROCESS_KEY = M.K6 THEN D.DB_BALANCE_AVG_AMT END) AS SALDO_INV_M6,
        SUM(CASE WHEN D.PROCESS_KEY = M.K5 THEN D.DB_BALANCE_AVG_AMT END) AS SALDO_INV_M5,
        SUM(CASE WHEN D.PROCESS_KEY = M.K4 THEN D.DB_BALANCE_AVG_AMT END) AS SALDO_INV_M4,
        SUM(CASE WHEN D.PROCESS_KEY = M.K3 THEN D.DB_BALANCE_AVG_AMT END) AS SALDO_INV_M3,
        SUM(CASE WHEN D.PROCESS_KEY = M.K2 THEN D.DB_BALANCE_AVG_AMT END) AS SALDO_INV_M2,
        SUM(CASE WHEN D.PROCESS_KEY = M.K1 THEN D.DB_BALANCE_AVG_AMT END) AS SALDO_INV_M1,
        SUM(CASE WHEN D.PROCESS_KEY = M.K0 THEN D.DB_BALANCE_AVG_AMT END) AS SALDO_INV_M0
    FROM Datos_SALDOS_INVER AS D
    CROSS JOIN MESES AS M
    WHERE D.REG = 1 
      AND D.PIVOT_ACCOUNT_ID IN (SELECT PIVOT_ACCOUNT_ID FROM UNIVERSO_INVER70)
    GROUP BY D.CUSTOMER_ID, D.PIVOT_ACCOUNT_ID
    ),

    --Tabla TXN_CTE
    TXN_CTE AS (
        SELECT UNI.NUM_CLIENTE,
        UNI.CUENTA_AHORRO,
        UNI.SALDO_CORTE,
        UNI.ANTIGUEDAD_AHORRO,
        UNI.OFICINA_SERVICIO,
        SAHC.SALDO_CORTE_AH_M0, SAHC.SALDO_CORTE_AH_M1,SAHC.SALDO_CORTE_AH_M2,SAHC.SALDO_CORTE_AH_M3,SAHC.SALDO_CORTE_AH_M4,
        SAHC.SALDO_CORTE_AH_M5,SAHC.SALDO_CORTE_AH_M6,SAHC.SALDO_CORTE_AH_M7,SAHC.SALDO_CORTE_AH_M8,
        SAH.SALDO_AH_M0,SAH.SALDO_AH_M1,SAH.SALDO_AH_M2,SAH.SALDO_AH_M3,SAH.SALDO_AH_M4,
        SAH.SALDO_AH_M5,SAH.SALDO_AH_M6,SAH.SALDO_AH_M7,SAH.SALDO_AH_M8,
        SINV.SALDO_INV_M0,SINV.SALDO_INV_M1,SINV.SALDO_INV_M2,SINV.SALDO_INV_M3,SINV.SALDO_INV_M4,
        SINV.SALDO_INV_M5,SINV.SALDO_INV_M6,SINV.SALDO_INV_M7,SINV.SALDO_INV_M8,
        TXI.MONTO_TRANSAC_IN_M0,TXI.MONTO_TRANSAC_IN_M1,TXI.MONTO_TRANSAC_IN_M2,TXI.MONTO_TRANSAC_IN_M3,TXI.MONTO_TRANSAC_IN_M4,
        TXI.MONTO_TRANSAC_IN_M5, TXI.MONTO_TRANSAC_IN_M6, TXI.MONTO_TRANSAC_IN_M7,TXI.MONTO_TRANSAC_IN_M8,
        TXI.TOT_MONTO_TX_IN_M0,TXI.TOT_MONTO_TX_IN_M1,TXI.TOT_MONTO_TX_IN_M2,TXI.TOT_MONTO_TX_IN_M3,TXI.TOT_MONTO_TX_IN_M4,
        TXI.TOT_MONTO_TX_IN_M5,TXI.TOT_MONTO_TX_IN_M6,TXI.TOT_MONTO_TX_IN_M7,TXI.TOT_MONTO_TX_IN_M8,
        TXOUT.TOT_MONTO_TX_OUT_M0,TXOUT.TOT_MONTO_TX_OUT_M1,TXOUT.TOT_MONTO_TX_OUT_M2,TXOUT.TOT_MONTO_TX_OUT_M3,TXOUT.TOT_MONTO_TX_OUT_M4,
        TXOUT.TOT_MONTO_TX_OUT_M5,TXOUT.TOT_MONTO_TX_OUT_M6,TXOUT.TOT_MONTO_TX_OUT_M7,TXOUT.TOT_MONTO_TX_OUT_M8,
        SI.MONTO_SPEI_IN_M0,SI.MONTO_SPEI_IN_M1,SI.MONTO_SPEI_IN_M2,SI.MONTO_SPEI_IN_M3,SI.MONTO_SPEI_IN_M4,
        SI.MONTO_SPEI_IN_M5,SI.MONTO_SPEI_IN_M6,SI.MONTO_SPEI_IN_M7,SI.MONTO_SPEI_IN_M8,
        SI.TOT_SPEI_TX_IN_M0,SI.TOT_SPEI_TX_IN_M1,
        SO.MONTO_SPEI_OUT_M0,SO.MONTO_SPEI_OUT_M1,SO.MONTO_SPEI_OUT_M2,SO.MONTO_SPEI_OUT_M3,SO.MONTO_SPEI_OUT_M4,
        SO.MONTO_SPEI_OUT_M5,SO.MONTO_SPEI_OUT_M6,SO.MONTO_SPEI_OUT_M7,SO.MONTO_SPEI_OUT_M8,
        DC.MONTO_DESEM_CRED_IN_M0,DC.MONTO_DESEM_CRED_IN_M1,DC.MONTO_DESEM_CRED_IN_M2,DC.MONTO_DESEM_CRED_IN_M3,DC.MONTO_DESEM_CRED_IN_M4,
        DC.MONTO_DESEM_CRED_IN_M5,DC.MONTO_DESEM_CRED_IN_M6,DC.MONTO_DESEM_CRED_IN_M7,DC.MONTO_DESEM_CRED_IN_M8,
        CO.MONTO_COMPRAS_OUT_M0,CO.MONTO_COMPRAS_OUT_M1,CO.MONTO_COMPRAS_OUT_M2,CO.MONTO_COMPRAS_OUT_M3,CO.MONTO_COMPRAS_OUT_M4,
        CO.MONTO_COMPRAS_OUT_M5,CO.MONTO_COMPRAS_OUT_M6,CO.MONTO_COMPRAS_OUT_M7,CO.MONTO_COMPRAS_OUT_M8,
        CO.TOT_COMPRAS_TX_OUT_M0,CO.TOT_COMPRAS_TX_OUT_M1,CO.TOT_COMPRAS_TX_OUT_M2,CO.TOT_COMPRAS_TX_OUT_M3,CO.TOT_COMPRAS_TX_OUT_M4,
        CO.TOT_COMPRAS_TX_OUT_M5,CO.TOT_COMPRAS_TX_OUT_M6,CO.TOT_COMPRAS_TX_OUT_M7,CO.TOT_COMPRAS_TX_OUT_M8
    FROM UNIVERSO_INVER37_64 AS UNI
        LEFT JOIN TX_IN AS TXI ON (TXI.NUM_CUENTA_AHORRO=UNI.NUM_CUENTA_AHORRO)
        LEFT JOIN TX_OUT AS TXOUT ON (TXOUT.NUM_CUENTA_AHORRO=UNI.NUM_CUENTA_AHORRO)
        LEFT JOIN SALDOS_AH AS SAH ON (SAH.CUSTOMER_ID=UNI.NUM_CLIENTE AND SAH.account_id=UNI.NUM_CUENTA_AHORRO)
        LEFT JOIN SALDOS_AH_CORTE AS SAHC ON (SAHC.CUSTOMER_ID=UNI.NUM_CLIENTE AND SAHC.account_id=UNI.NUM_CUENTA_AHORRO)
        LEFT JOIN SALDOS_INVER AS SINV ON (SINV.CUSTOMER_ID=UNI.NUM_CLIENTE AND SINV.PIVOT_ACCOUNT_ID=UNI.NUM_CUENTA_AHORRO)
        LEFT JOIN SPEI_IN AS SI ON (SI.NUM_CUENTA_AHORRO=UNI.NUM_CUENTA_AHORRO)
        LEFT JOIN SPEI_OUT AS SO ON (SO.NUM_CUENTA_AHORRO=UNI.NUM_CUENTA_AHORRO)
        LEFT JOIN DESEM_CRED_IN AS DC ON (DC.NUM_CUENTA_AHORRO=UNI.NUM_CUENTA_AHORRO)
        LEFT JOIN COMPRAS_OUT AS CO ON (CO.NUM_CUENTA_AHORRO=UNI.NUM_CUENTA_AHORRO)
    ),

    -- Tabla CTES
    CTES AS (
    SELECT customer_id,
        YEARS_BETWEEN(BIRTH_DT, CAST(SESSION_CONTEXT('FECHA') AS DATE)) AS EDAD,
        CHILD_QTY as HIJOS,
        ZIP_NUM AS CP,
    FROM DP_SEM_EXP.DIM_CUSTOMER_HIST
    WHERE customer_id IN (SELECT DISTINCT(num_cliente) FROM UNIVERSO_INVER37_64)
        AND LAST_DAY(CAST(SESSION_CONTEXT('FECHA') AS DATE)) BETWEEN CUSTOMER_START_DT AND coalesce(CUSTOMER_END_DT,cast('9999-01-01' as date))
    ), 

    CRED AS(
    SELECT * FROM (
    SELECT 
        C.CUSTOMER_ID,
        DCDH.DISBMNT_AMT AS MONTO_DESEMBOLSO
        ,ROW_NUMBER() OVER (PARTITION BY C.CUSTOMER_ID ORDER BY C.CONTRACT_START_DT desc) AS REG
    FROM DP_SEM_EXP.CONTRACT_HEADER_ATOMIC_HIST AS C
    INNER JOIN DP_SEM_EXP.DIM_CONTRACT_DISBURSEMENT_HIST AS DCDH 
    	ON (C.CONTRACT_ID=DCDH.CONTRACT_ID 
    	AND DCDH.DISBMNT_DT <= LAST_DAY(CAST(SESSION_CONTEXT('FECHA') AS DATE)) 
        AND ADD_DAYS(C.CONTRACT_START_DT,7) BETWEEN DCDH.CONTRACT_DISBMNT_START_DT AND coalesce(DCDH.CONTRACT_DISBMNT_END_DT,'9999-01-01') 
        AND DCDH.DISBMNT_STATUS_CD IN (103, 1)
        AND (DISBMNT_METHOD_CD||'|'||DISB_BUSINESS_STAT_CD) IN ('3|27','3|35','1|7','1|9','1|13','1|20','1|4','4|44','4|47'))
    WHERE C.PRODUCT_ID IN (4,23,30,170)
    AND C.CONTRACT_STATUS_CD IN (1,28,6,7)
    AND C.CUSTOMER_ID IN (SELECT distinct(num_cliente) FROM UNIVERSO_INVER37_64)
    AND LAST_DAY(CAST(SESSION_CONTEXT('FECHA') AS DATE)) BETWEEN C.CONTRACT_ATOMIC_START_DT AND coalesce(C.CONTRACT_ATOMIC_END_DT,cast('9999-01-01' as date))
    ) WHERE REG=1
    )

-- Consulta Final de la Sabana
SELECT
TC.NUM_CLIENTE,
TC.CUENTA_AHORRO,
TC.ANTIGUEDAD_AHORRO,
TC.OFICINA_SERVICIO,
TC.SALDO_CORTE,
TC.SALDO_CORTE_AH_M0, TC.SALDO_CORTE_AH_M1, TC.SALDO_CORTE_AH_M2, TC.SALDO_CORTE_AH_M3, TC.SALDO_CORTE_AH_M4,
TC.SALDO_CORTE_AH_M5, TC.SALDO_CORTE_AH_M6, TC.SALDO_CORTE_AH_M7, TC.SALDO_CORTE_AH_M8,
TC.SALDO_AH_M0, TC.SALDO_AH_M1, TC.SALDO_AH_M2, TC.SALDO_AH_M3, TC.SALDO_AH_M4,
TC.SALDO_AH_M5, TC.SALDO_AH_M6, TC.SALDO_AH_M7, TC.SALDO_AH_M8,
TC.SALDO_INV_M0, TC.SALDO_INV_M1, TC.SALDO_INV_M2, TC.SALDO_INV_M3, TC.SALDO_INV_M4,
TC.SALDO_INV_M5, TC.SALDO_INV_M6, TC.SALDO_INV_M7, TC.SALDO_INV_M8,
TC.MONTO_TRANSAC_IN_M0 AS MONTO_TX_IN_M0,TC.MONTO_TRANSAC_IN_M1 AS MONTO_TX_IN_M1,
TC.MONTO_TRANSAC_IN_M2 AS MONTO_TX_IN_M2,TC.MONTO_TRANSAC_IN_M3 AS MONTO_TX_IN_M3,
TC.MONTO_TRANSAC_IN_M4 AS MONTO_TX_IN_M4,TC.MONTO_TRANSAC_IN_M5 AS MONTO_TX_IN_M5,
TC.MONTO_TRANSAC_IN_M6 AS MONTO_TX_IN_M6,TC.MONTO_TRANSAC_IN_M7 AS MONTO_TX_IN_M7,
TC.MONTO_TRANSAC_IN_M8 AS MONTO_TX_IN_M8,
COALESCE(TC.TOT_MONTO_TX_IN_M0, 0) AS TOT_TX_IN_M0, COALESCE(TC.TOT_MONTO_TX_IN_M1, 0) AS TOT_TX_IN_M1,
COALESCE(TC.TOT_MONTO_TX_IN_M2, 0) AS TOT_TX_IN_M2, COALESCE(TC.TOT_MONTO_TX_IN_M3, 0) AS TOT_TX_IN_M3,
COALESCE(TC.TOT_MONTO_TX_IN_M4, 0) AS TOT_TX_IN_M4, COALESCE(TC.TOT_MONTO_TX_IN_M5, 0) AS TOT_TX_IN_M5,
COALESCE(TC.TOT_MONTO_TX_IN_M6, 0) AS TOT_TX_IN_M6, COALESCE(TC.TOT_MONTO_TX_IN_M7, 0) AS TOT_TX_IN_M7,
COALESCE(TC.TOT_MONTO_TX_IN_M8, 0) AS TOT_TX_IN_M8,
COALESCE(TC.TOT_MONTO_TX_OUT_M0, 0) AS TOT_TX_OUT_M0, COALESCE(TC.TOT_MONTO_TX_OUT_M1, 0) AS TOT_TX_OUT_M1,
COALESCE(TC.TOT_MONTO_TX_OUT_M2, 0) AS TOT_TX_OUT_M2, COALESCE(TC.TOT_MONTO_TX_OUT_M3, 0) AS TOT_TX_OUT_M3,
COALESCE(TC.TOT_MONTO_TX_OUT_M4, 0) AS TOT_TX_OUT_M4, COALESCE(TC.TOT_MONTO_TX_OUT_M5, 0) AS TOT_TX_OUT_M5,
COALESCE(TC.TOT_MONTO_TX_OUT_M6, 0) AS TOT_TX_OUT_M6, COALESCE(TC.TOT_MONTO_TX_OUT_M7, 0) AS TOT_TX_OUT_M7,
COALESCE(TC.TOT_MONTO_TX_OUT_M8, 0) AS TOT_TX_OUT_M8,
TC.MONTO_SPEI_IN_M0, TC.MONTO_SPEI_IN_M1, TC.MONTO_SPEI_IN_M2, TC.MONTO_SPEI_IN_M3, TC.MONTO_SPEI_IN_M4,
TC.MONTO_SPEI_IN_M5, TC.MONTO_SPEI_IN_M6, TC.MONTO_SPEI_IN_M7, TC.MONTO_SPEI_IN_M8,
COALESCE(TC.TOT_SPEI_TX_IN_M0, 0) AS TOT_SPEI_TX_IN_M0, COALESCE(TC.TOT_SPEI_TX_IN_M1, 0) AS TOT_SPEI_TX_IN_M1,
TC.MONTO_SPEI_OUT_M0, TC.MONTO_SPEI_OUT_M1, TC.MONTO_SPEI_OUT_M2, TC.MONTO_SPEI_OUT_M3, TC.MONTO_SPEI_OUT_M4,
TC.MONTO_SPEI_OUT_M5, TC.MONTO_SPEI_OUT_M6, TC.MONTO_SPEI_OUT_M7, TC.MONTO_SPEI_OUT_M8,
TC.MONTO_DESEM_CRED_IN_M0, TC.MONTO_DESEM_CRED_IN_M1, TC.MONTO_DESEM_CRED_IN_M2, TC.MONTO_DESEM_CRED_IN_M3, TC.MONTO_DESEM_CRED_IN_M4,
TC.MONTO_DESEM_CRED_IN_M5, TC.MONTO_DESEM_CRED_IN_M6, TC.MONTO_DESEM_CRED_IN_M7, TC.MONTO_DESEM_CRED_IN_M8,
TC.MONTO_COMPRAS_OUT_M0, TC.MONTO_COMPRAS_OUT_M1, TC.MONTO_COMPRAS_OUT_M2, TC.MONTO_COMPRAS_OUT_M3, TC.MONTO_COMPRAS_OUT_M4,
TC.MONTO_COMPRAS_OUT_M5, TC.MONTO_COMPRAS_OUT_M6, TC.MONTO_COMPRAS_OUT_M7, TC.MONTO_COMPRAS_OUT_M8,
COALESCE(TC.TOT_COMPRAS_TX_OUT_M0, 0) AS TOT_COMPRAS_TX_OUT_M0, COALESCE(TC.TOT_COMPRAS_TX_OUT_M1, 0) AS TOT_COMPRAS_TX_OUT_M1, 
COALESCE(TC.TOT_COMPRAS_TX_OUT_M2, 0) AS TOT_COMPRAS_TX_OUT_M2, COALESCE(TC.TOT_COMPRAS_TX_OUT_M3, 0) AS TOT_COMPRAS_TX_OUT_M3,
COALESCE(TC.TOT_COMPRAS_TX_OUT_M4, 0) AS TOT_COMPRAS_TX_OUT_M4, COALESCE(TC.TOT_COMPRAS_TX_OUT_M5, 0) AS TOT_COMPRAS_TX_OUT_M5, 
COALESCE(TC.TOT_COMPRAS_TX_OUT_M6, 0) AS TOT_COMPRAS_TX_OUT_M6, COALESCE(TC.TOT_COMPRAS_TX_OUT_M7, 0) AS TOT_COMPRAS_TX_OUT_M7, 
COALESCE(TC.TOT_COMPRAS_TX_OUT_M8, 0) AS TOT_COMPRAS_TX_OUT_M8,  
CTE.EDAD,
CTE.HIJOS,
CTE.CP,
CRED.MONTO_DESEMBOLSO
FROM TXN_CTE AS TC
LEFT JOIN CTES AS CTE ON (TC.num_cliente=CTE.customer_id)
LEFT JOIN CRED AS CRED ON (TC.num_cliente=CRED.customer_id)